export const READER_SIDEBAR_WIDTH_PX = 384;
export const READER_MOBILE_LAYOUT_BREAKPOINT_PX = 1024;

export const LIBRARY_PROJECT_MENU_WIDTH_PX = 176;
export const LIBRARY_MENU_GAP_PX = 8;
export const LIBRARY_MENU_EDGE_PADDING_PX = 12;
export const LIBRARY_PROJECT_MENU_ESTIMATED_HEIGHT_PX = 188;
export const LIBRARY_FOLDER_MENU_ESTIMATED_HEIGHT_PX = 272;
