export const READER_SIDEBAR_WIDTH_PX = 384;
export const READER_MOBILE_LAYOUT_BREAKPOINT_PX = 1024;
export const READER_MOBILE_TOP_FADE_HEIGHT_PX = 96;
export const READER_MOBILE_INITIAL_TOP_OFFSET_PX = READER_MOBILE_TOP_FADE_HEIGHT_PX;
export const READER_MOBILE_BOTTOM_FADE_HEIGHT_PX = 54;
export const READER_MOBILE_BOTTOM_FADE_MIN_ALPHA = 0.7025;
export const READER_MOBILE_TOP_FADE_SCROLL_RANGE_PX = 50;
export const READER_MOBILE_TOP_FADE_ALPHA_PROPERTY = '--reader-mobile-top-fade-alpha';
