export const MAX_LESSON_SOURCE_CONTEXT_CHARS = 16_000;
export const MAX_LESSON_COMBINED_SOURCE_CONTEXT_CHARS = 36_000;
export const MAX_LESSON_CONTEXT_CHUNKS = 6;
export const DEFAULT_LESSON_CONTEXT_CHUNKS = 2;
