export const PDF_TEXT_CHUNK_TARGET_CHARS = 7_000;
export const PDF_TEXT_CHUNK_MIN_CHARS = 3_500;
export const PDF_TEXT_CHUNK_MAX_CHARS = 9_500;
export const PDF_TEXT_SOURCE_CHUNK_CHARS = 8_000;
export const PDF_PAGE_TEXT_SEPARATOR = '\n\n';

export const PDF_MAPPING_MAX_PRIMARY_CHUNKS_PER_LESSON = 3;
export const PDF_MAPPING_MAX_LESSONS_PER_REQUEST = 8;
export const PDF_MAPPING_MAX_LESSON_JSON_CHARS = 7_000;
export const PDF_MAPPING_TARGET_PROMPT_CHARS = 180_000;
export const PDF_MAPPING_MIN_CHUNK_PREVIEW_CHARS = 96;
export const PDF_MAPPING_MAX_CHUNK_PREVIEW_CHARS = 480;
export const PDF_MAPPING_REPAIR_MAX_LESSONS_PER_REQUEST = 1;
export const PDF_MAPPING_MIN_CHUNK_CANDIDATES = 36;
export const PDF_MAPPING_MAX_CHUNK_CANDIDATES = 96;
export const PDF_MAPPING_CHUNK_WINDOW_PADDING = 12;
export const PDF_MAPPING_REPAIR_MIN_CHUNK_CANDIDATES = 20;
export const PDF_MAPPING_REPAIR_MAX_CHUNK_CANDIDATES = 32;
export const PDF_MAPPING_REPAIR_CHUNK_WINDOW_PADDING = 5;
export const PDF_MAPPING_RECOVERY_EXHAUSTED_WARNING =
  'Il mapping automatico del PDF non è riuscito dopo tutti i tentativi. Il corso continuerà a usare associazioni di fallback senza riprovare a ogni apertura.';

export const PDF_PLAN_EDGE_EXCLUSION_RATIO = 0.05;
export const PDF_PLAN_MAX_EDGE_PAGES = 6;
export const PDF_PLAN_MIN_PAGES_FOR_EDGE_EXCLUSION = 18;

export const PDF_TEXT_QUALITY = {
  MIN_SHORT_DOCUMENT_CHARS: 240,
  MIN_MULTI_PAGE_DOCUMENT_CHARS: 800,
  SHORT_DOCUMENT_MAX_PAGES: 2,
  MIN_AVERAGE_CHARS_PER_PAGE: 35,
  MIN_TEXT_PAGE_RATIO: 0.1,
  SUBSTANTIVE_PAGE_MIN_CHARS: 80,
} as const;
